### ISSUE TITLE
build information splash page

### ISSUE THREAD

**Issue by DevanB** [DevanB/wtgs#11]
Splash page with artwork, short blurb about the project and mailing list signup

**Comment by DevanB** [comment]
Sending this your way. You should have enough to write the intro or whatnot.

**Comment by dimwell** [comment]
I updated the intro. Should be good to go.

**Comment by DevanB** [comment]
Great. I'll finish up the mail chimp stuff, add some new markers and get it deployed.

**Comment by DevanB** [comment]
Completed and deployed.
