### ISSUE TITLE
Add generic markers to map

### ISSUE THREAD

**Issue by DevanB** [DevanB/wtgs#12]

**Comment by DevanB** [comment]
We should get our hands on some more data to add to Mississippi, Georgia, South Carolina, and Arkansas :) @chrisbrightwell

**Comment by dimwell** [comment]
I'll start gathering the data, but I'm not building another JSON file by hand. Get me a database!

**Comment by DevanB** [comment]
I started the admin area! It'll be in a day or two:p

**Comment by dimwell** [comment]
I added a bunch of national parks data. I found a list of all 50-something parks with lat/lon on Wikipedia, so this was pretty easy to stub out.

**Comment by DevanB** [comment]
Completed and deployed.
