### ISSUE TITLE
Hitting Enter in the email form doesn't submit the form.

### ISSUE THREAD

**Issue by dimwell** [DevanB/wtgs#20]
See title. Appears to just reload the page.

**Comment by dimwell** [comment]
Okay, so it appears that it does submit the form, but it doesn't give the "Success!" indicator.

**Comment by DevanB** [comment]
1. I see the reload page issue. Looking into it.
2. When you don't use enter to submit email it tells you to check your email.

**Comment by DevanB** [comment]
Deployed.
