### ISSUE TITLE
Allow user to dismiss modal box.

### ISSUE THREAD

**Issue by dimwell** [DevanB/wtgs#21]
Two options:
1. Give us an email.
2. Click an "X" in the corner somewhere.

Both should dismiss the modal box.

**Comment by DevanB** [comment]
Begin able to close the modal adds what advantage? (just playing devil’s advocate)

Also, if user closes modal and later wants to give email, they have to refresh page. You okay with this?

**Comment by dimwell** [comment]
> Begin able to close the modal adds what advantage? (just playing devil’s
> advocate)

It lets them poke around the data and view the current prototype.

> Also, if user closes modal and later wants to give email, they have to
> refresh page. You okay with this?

Yes. I figure that the "X" and the email submit are intentional enough to
be okay. If they can dismiss via accidental click on the background, that
might be an issue.

**Comment by DevanB** [comment]
Cool. Just throwing some questions out there.

**Comment by DevanB** [comment]
I think closing modal on email subscribe isn't such a great UX. User needs to see if the email succeeded because it tells them to check their email.

Yes, I just checked on wheretogoscouting.org and it is giving feedback after subscription. Not sure why you aren't seeing it.

**Comment by dimwell** [comment]
Leaving it open after email confirmation is fine.

**Comment by DevanB** [comment]
Yeah, I think this is the best UX.

This has been deployed.
