### ISSUE TITLE
Add a "DEVELOPMENT PREVIEW" indicator to the NOAC demo.

### ISSUE THREAD

**Issue by dimwell** [DevanB/wtgs#22]
Feel free to swipe the look and feel of the black/grey overlay I built in the leaflet branch.

**Comment by DevanB** [comment]
You going to add this to the bottom left of the page?

**Comment by dimwell** [comment]
Probably, yeah. Any objection?

**Comment by DevanB** [comment]
None at all. I'll let you handle it :)

**Comment by DevanB** [comment]
Deployed
