### ISSUE TITLE
Add About WTGS page

### ISSUE THREAD

**Issue by DevanB** [DevanB/wtgs#25]
Add About WTGS

Edit in admin area. 

Markdown?

**Comment by dimwell** [comment]
If we're going to support formatting in text fields, yes, use Markdown.

**Comment by DevanB** [comment]
Are you fine creating/managing content in Markdown then?

**Comment by DevanB** [comment]
This is good to go also. It will be part of the big merge and redeploy.

**Comment by DevanB** [comment]
Deployed. 4871d49
